### ISSUE TITLE
Remove dependency to gwtquery

### ISSUE THREAD

**Issue by gilberto-torrezan** [wokier/gwt-fullscreen#2]
Making the project self-contained will reduce problems in the future when new versions of gwtquery (or any other direct dependencies) get released.

**Comment by wokier** [comment]
gwtquery is the only dependency, and i can't imagine doing anything without it.

**Comment by gilberto-torrezan** [comment]
So sad, I'll have to create a "gwt-fullscreen" project myself =/

Thanks for the initiative.

**Comment by wokier** [comment]
You can even fork this one
